# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/uart-pl/Zybo-Z7-Master.xdc

# Block Designs: bd/uart_pl/uart_pl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl || ORIG_REF_NAME==uart_pl} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_Blinker_0_0/uart_pl_Blinker_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_Blinker_0_0 || ORIG_REF_NAME==uart_pl_Blinker_0_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_processing_system7_0_0/uart_pl_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_processing_system7_0_0 || ORIG_REF_NAME==uart_pl_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_axi_gpio_0_0/uart_pl_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_axi_gpio_0_0 || ORIG_REF_NAME==uart_pl_axi_gpio_0_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_axi_gpio_1_0/uart_pl_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_axi_gpio_1_0 || ORIG_REF_NAME==uart_pl_axi_gpio_1_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_xbar_0/uart_pl_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_xbar_0 || ORIG_REF_NAME==uart_pl_xbar_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_ps7_0_axi_periph_0/uart_pl_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_pl_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_rst_ps7_0_50M_0/uart_pl_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_rst_ps7_0_50M_0 || ORIG_REF_NAME==uart_pl_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_axi_gpio_2_0/uart_pl_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_axi_gpio_2_0 || ORIG_REF_NAME==uart_pl_axi_gpio_2_0} -quiet] -quiet

# IP: bd/uart_pl/ip/uart_pl_auto_pc_0/uart_pl_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_pl_auto_pc_0 || ORIG_REF_NAME==uart_pl_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/darkr/Documents/vivadoProjects/uart-pl/uart-pl.gen/sources_1/bd/uart_pl/uart_pl_ooc.xdc
